/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_DART-FFI__
#define __RUST_DART-FFI__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

void hash_free (
    uint8_t * data);

uint8_t const * hash (
    uint8_t const * data,
    size_t len);

typedef struct Hasher Hasher_t;

Hasher_t * hasher_new (void);

void hasher_update (
    Hasher_t * hasher,
    uint8_t const * data,
    size_t len);

uint8_t const * hasher_end (
    Hasher_t * hasher);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_DART-FFI__ */
